
baseURL: "https://resume.c-aubry.be/"
languageCode: "en-us"
title: "Christophe Aubry"
params:
  background: "images/background.jpg"
  footer:
    contactMe:
      enable: true
    newsletter:
      enable: false
module:
  imports:
    path: 'github.com/hugo-toha/toha/v4'

