name: Deploy to Github Pages

# run when a commit is pushed to "source" branch
on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout to the commit that has been pushed
    - uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.152.2'
        extended: true

    - name: Update Hugo Modules
      run: hugo mod tidy

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Install node modules
      run: |
        hugo mod npm pack
        npm install

    - name: Build
      run: hugo --minify

    - name: Publish on surge.sh
      run: |
        npm install --global surge
        npx surge ./public https://portfolio.c-aubry.be
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
