name: Deploy to surge.sh

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: 24
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.152.2'
        extended: true

    - name: Update Hugo Modules
      run: hugo mod tidy

    - name: Install node modules
      run: |
        hugo mod npm pack
        npm install

    - name: Build
      run: hugo --minify

    - name: Publish on surge.sh
      run: |
        npm install --global surge
        npx surge ./public https://portfolio.c-aubry.be
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
